nsinya/api/urls.py
from django.conf.urls import url
from .views import GxAlertCreateAPIView, WidgetAPIView, ServerStatusAPIView, GxConnectCreateAPIView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    url(r'^api-token-auth/', obtain_auth_token),
    url(r'^gx/v1/gxa/test$', GxAlertCreateAPIView.as_view(), name='api-gx-alert-test'),
    url(r'^gx/v2/connect/ping$', ServerStatusAPIView.as_view(), name='api-gx-server-status'),
    url(r'^gx/v2/connect/dailydetails$', ServerStatusAPIView.as_view(), name='api-gx-daily-details'),
    url(r'^gx/v2/connect/test$', GxConnectCreateAPIView.as_view(), name='api-gx-connect-test'),
    url(r'^widget/v1/$', WidgetAPIView.as_view(), name='api-widget'),
]

nsinya/urls.py
from django.conf.urls import include, url
from .views import *

app_name = 'nsinya'

urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api/', include('nsinya.api.urls')),
    url(r'^census/eligibility/$', CheckEligibilityView.as_view(), name="check-eligibility"),
    url(r'^census/eligibility/(?P<pin>[\w{}.-]+)/$', CheckEligibilityView.as_view(), name="check-eligibility"),
    url(r'^census/participants/$', ParticipantListingView.as_view(), name="participant-listing"),
    url(r'^census/participant/(?P<pin>[\w{}.-]+)/$', ParticipantDashboardView.as_view(), name="participant-dashboard"),
    url(r'^census/households/$', HouseholdListingView.as_view(), name="household-listing"),
    url(r'^census/household/(?P<household_id>[\w{}.-]+)/$', HouseholdDashboardView.as_view(), name="household-dashboard"),
    url(r'^diagnosis/sampletracking/$', SampleTrackingView.as_view(), name="sample-tracking"),
    url(r'^diagnosis/sample/(?P<sample_id>.+)/$', SampleDashboardView.as_view(), name="sample-tracking-dashboard"),
    url(r'^diagnosis/medical_review_panel/$', MedicalReviewPanelView.as_view(), name="medical-review_panel"),
    url(r'^diagnosis/review_participant/(?P<pin>[\w{}.-]+)/$', ReviewParticipantView.as_view(), name="review-participant"),
    url(r'^radiology/central_cxr_reading_list/$', CentralCXRReadingList.as_view(), name="central-cxr-reading-list"),
    url(r'^radiology/central_cxr_reading/(?P<pin>[\w{}.-]+)/$', CentralCXRReading.as_view(), name="read-participant-cxr"),
    url(r'^crl/reception/$', BatchReceptionView.as_view(), name="batch-reception"),
    url(r'^crl/receive/batch/(?P<batch_id>[0-9]+)/$', ReceiveBatchView.as_view(), name="receive-batch"),
    url(r'^crl/receive/sample/(?P<batch_id>[0-9]+)/$', ReceiveSampleView.as_view(), name="receive-sample"),
    url(r'^crl/receive/sample/(?P<batch_id>[0-9]+)/(?P<sample_id>\w+)/$', ReceiveSampleView.as_view(), name="receive-sample"),
    url(r'^crl/orphan_sample/$', ReceiveOrphanSampleView.as_view(), name="receive-orphan-sample"),
    url(r'^crl/orphan_sample/(?P<sample_id>\w+)/$', ReceiveOrphanSampleView.as_view(), name="receive-orphan-sample"),
    url(r'^crl/culture/$', CultureListingView.as_view(), name="culture-listing"),
    url(r'^crl/culture_reading/$', CultureReadingView.as_view(), name="culture-reading"),
    url(r'^crl/culture_reading/(?P<sample_id>\w+)/$', CultureReadingView.as_view(), name="culture-reading"),
    url(r'^crl/culture_edit/(?P<culture_id>\w+)/$', CultureEditView.as_view(), name="culture-edit"),
    url(r'^crl/culture_validation/$', CultureValidationView.as_view(), name="culture-validation"),
    url(r'^crl/culture_validation/(?P<sample_id>.+)/$', CultureValidationView.as_view(), name="culture-validation"),
    url(r'^crl/culture/validate/(?P<culture_id>.+)/$', ValidateCultureView.as_view(), name="validate-culture"),
    url(r'^crl/cultures/validate/$', ValidateCulturesView.as_view(), name="validate-cultures"),
    url(r'^crl/cultures/validate/(?P<sample_id>\w+)/$', ValidateCulturesView.as_view(), name="validate-cultures"),
    url(r'^crl/tsa/$', TSAListingView.as_view(), name="tsa-listing"),
    url(r'^crl/tsa/create/$', TSACreateView.as_view(), name="create-tsa"),
    url(r'^crl/tsa/create/(?P<sample_id>\w+)/$', TSACreateView.as_view(), name="create-tsa"),
    url(r'^crl/tsa_validation/$', TSAValidationView.as_view(), name="tsa-validation"),
    url(r'^crl/smear/$', SmearListingView.as_view(), name="smear-listing"),
    url(r'^crl/smear/(?P<sample_id>\w+)/$', SmearListingView.as_view(), name="smear-listing"),
    url(r'^crl/smear_validation/$', ValidateSmearView.as_view(), name="validate-smear"),
    url(r'^crl/smear_validation/(?P<sample_id>.+)/$', ValidateSmearView.as_view(), name="validate-smear"),
    url(r'^crl/worksheet/$', WorksheetView.as_view(), name="worksheet-creation"),
    url(r'^crl/worksheet/(?P<sample_id>\w+)/$', WorksheetView.as_view(), name="worksheet-creation"),
    url(r'^crl/worksheet/(?P<sample_id>\w+)/(?P<remove>\w+)$', WorksheetView.as_view(), name="worksheet-creation"),
    url(r'^crl/worksheet_select_type/(?P<sample_id>\w+)/(?P<type>\w+)$', WorksheetView.as_view(), name="worksheet-creation"),
    url(r'^crl/worksheet_select_type/(?P<type>\w+)/$', WorksheetView.as_view(), name="worksheet-creation"),
    url(r'^crl/worksheet_details/(?P<worksheet_code>[\w{}.-]+)/$', WorksheetDetailsView.as_view(), name="worksheet-details"),
    url(r'^crl/worksheetlist/$', WorksheetListView.as_view(), name="worksheet-list"),
    url(r'^crl/worksheetlist/(?P<worksheet_id>\w+)/$', WorksheetListView.as_view(), name="worksheet-list"),
    url(r'^crl/worksheetedit/(?P<worksheet_id>\w+)/$', WorksheetEditView.as_view(), name="worksheet-edit"),
    url(r'^crl/worksheetedit/(?P<sample_id>\w+)/(?P<worksheet_id>\w+)/(?P<remove>\w+)$', WorksheetEditView.as_view(), name="worksheet-edit-list"),
    url(r'^crl/inoculation/$', WorksheetInoculationView.as_view(), name="worksheet-inoculation"),
    url(r'^crl/inoculation/(?P<worksheet_id>\w+)/$', WorksheetInoculationView.as_view(), name="worksheet-inoculation"),
    url(r'^diagnosis/genexpert/$', GeneXpertListingView.as_view(), name="genexpert-listing"),
    url(r'^config/clusters/$', ClusterActivationView.as_view(), name="cluster-activation"),
    url(r'^census/cluster/(?P<cluster_id>[0-9]+)/$', ClusterBatchesView.as_view(), name="cluster-batches"),
    url(r'^census/cluster/(?P<cluster_code>[0-9]+)/status/(?P<status>[0-9]+)/$', ClusterStatusUpdateView.as_view(), name="cluster-status-update"),
    url(r'^crl/genotype_cm/$', Genotype_CMListingView.as_view(), name="genotype_cm-listing"),
    url(r'^crl/genotype_cm/(?P<sample_id>\w+)/$', Genotype_CMListingView.as_view(), name="genotype_cm-listing"),
    url(r'^crl/genotype_cm_validation/$', ValidateGenotypeCmView.as_view(), name="validate-genotype_cm"),
    url(r'^crl/genotype_cm_validation/(?P<sample_id>.+)/$', ValidateGenotypeCmView.as_view(), name="validate-genotype_cm"),
    url(r'^crl/genotype_mt/$', Genotype_MTListingView.as_view(), name="genotype_mt-listing"),
    url(r'^crl/genotype_mt/(?P<sample_id>\w+)/$', Genotype_MTListingView.as_view(), name="genotype_mt-listing"),
    url(r'^crl/genotype_mt_validation/$', ValidateGenotypeMtView.as_view(), name="validate-genotype_mt"),
    url(r'^crl/genotype_mt_validation/(?P<sample_id>.+)/$', ValidateGenotypeMtView.as_view(), name="validate-genotype_mt"),
    url(r'^crl/ziehl/$', ZiehlListingView.as_view(), name="ziehl-listing"),
    url(r'^crl/ziehl/(?P<sample_id>\w+)/$', ZiehlListingView.as_view(), name="ziehl-listing"),
    url(r'^crl/ziehl_validation/$', ValidateZiehlView.as_view(), name="validate-ziehl"),
    url(r'^crl/ziehl_validation/(?P<sample_id>.+)/$', ValidateZiehlView.as_view(), name="validate-ziehl"),
]

nsinya/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MinLengthValidator, RegexValidator, MaxLengthValidator
from .choices import *
from audit_log.models import AuthStampedModel
from django.db.models import Max, ManyToManyField
from django.utils import timezone
from random import randint
import uuid

PARTICIPANT_SEQ_STEP = "1"

PARTICIPANT_SEQ_END_INDEX = 8

PARTICIPANT_SEQ_START_INDEX = 5


class AggregateModel(AuthStampedModel):
    uri = models.CharField(max_length=254)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    class Meta:
        abstract = True


class Census(AggregateModel):
    cluster_code = models.CharField(
        max_length=254,
        validators=[RegexValidator(
            regex=r'^[0-9]*$',
            message="O codigo do cluster deve conter apenas tres digitos numericos (001-999)"
        )])
    household_number = models.CharField(
        max_length=3,
        validators=[RegexValidator(
            regex=r'^[0-9]*$',
            message="O codigo do cluster deve conter apenas tres digitos numericos (001-999)"
        )])

    # The coordinates can be null because is still an open question in the requirements.
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    altitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)

    team_number = models.IntegerField(null=True, blank=True)
    province = models.CharField(max_length=100, null=True, blank=True)
    district = models.CharField(max_length=100, null=True, blank=True)
    administrative_post = models.CharField(max_length=100, null=True, blank=True)
    locality = models.CharField(max_length=100, null=True, blank=True)
    village = models.CharField(max_length=100, null=True, blank=True)

    residence_area = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=RESIDENCE_AREA_CHOICES,
        help_text='Zona onde reside?'
    )

    # household_head_name = models.CharField(max_length=100)
    # household_head_gender = models.CharField(
    #     max_length=254,
    #     choices=GENDER_CHOICES,
    #     help_text='Genero'
    # )

    household_type = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=HOUSEHOLD_TYPE_CHOICES,
        help_text='Tipo de Agregado'
    )

    household_type_other = models.CharField(max_length=100, null=True, blank=True)

    visit_result_end = models.CharField(
        max_length=254,
        choices=VISIT_RESULT_CHOICES,
        help_text='Resultado da Visita?',
        blank=True,
        null=True
    )

    visit_result_end_other = models.CharField(max_length=100, null=True, blank=True)

    interviewer_name = models.CharField(max_length=100, null=True, blank=True)

    house_compartments = models.IntegerField(null=True)

    compartments_for_sleep = models.IntegerField(null=True)

    house_building_material = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=BUILDING_MATERIAL_CHOICES,
        help_text='A quem pertence a habitaÁ„o onde vive o agregado familiar?'
    )

    house_building_material_other = models.CharField(max_length=100, null=True, blank=True)

    house_covering_material = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=COVERING_MATERIAL_CHOICES,
        help_text=' Material de cobertura?'
    )

    house_covering_material_other = models.CharField(max_length=100, null=True, blank=True)

    house_ownership_type = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=HOUSEHOLD_TYPE_CHOICES,
        help_text='Material de construncao?'
    )

    house_owner_ownership_other = models.CharField(max_length=100, null=True, blank=True)

    house_owning_method = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=HOUSE_OWNING_METHOD_CHOICES,
        help_text='Se a casa È prÛpria diga como a conseguiu?'
    )

    house_owning_method_other = models.CharField(max_length=100, null=True, blank=True)

    house_pavement_type = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=HOUSE_PAVEMENT_CHOICES,
        help_text='Pavimento da casa?'
    )

    house_pavement_type_other = models.CharField(max_length=100, null=True, blank=True)

    lighting_main_source = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=LIGHT_TYPE_CHOICES,
        help_text='Fonte de energia?'
    )

    lighting_main_source_other = models.CharField(max_length=100, null=True, blank=True)

    sanitation_type = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=SANITATION_TYPE_CHOICES,
        help_text='Onde È que os membros do seu agregado familiar fazem  as necessidades maiores??'
    )

    trash_treatment = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=TRASH_TREATMENT_CHOICES,
        help_text='Onde È que os membros do seu agregado familiar fazem  as necessidades maiores??'
    )

    trash_treatment_other = models.CharField(max_length=100, null=True, blank=True)

    water_main_source = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=WATER_MAIN_CHOICES,
        help_text='Onde È que os membros do seu agregado familiar fazem  as necessidades maiores??'
    )
    water_main_source_other = models.CharField(max_length=100, null=True, blank=True)

    visit_result_start = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=VISIT_RESULT_CHOICES,
        help_text='Resultado da Visita?'
    )

    visit_result_start_other = models.CharField(max_length=100, null=True, blank=True)

    visit_date = models.DateField()
    visit_number = models.IntegerField()

    status = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        # unique_together = ('cluster_code', 'household_number')
        verbose_name_plural = 'Census'

    def __str__(self):
        return '%s%s' % (self.cluster_code, self.household_number)


class Participant(AggregateModel):
    census = models.ForeignKey(
        Census,
        verbose_name="Participant's registration reference"
    )

    pin = models.CharField(
        max_length=9,
        unique=False,
        validators=[MinLengthValidator(7, 'O PIN deve conter nove digitos'),
                    MaxLengthValidator(7, 'O PIN deve conter nove digitos')])

    age = models.IntegerField(verbose_name="Idade")

    is_permanent_resident = models.CharField(
        max_length=1,
        null=True,
        blank=True,
        choices=RESIDENCE_PERMANENCE_CHOICES,
        help_text='Residente permanente no agregado?'
    )

    household_surname = models.CharField(max_length=100, null=True, blank=True)

    name = models.CharField(max_length=100)

    surname = models.CharField(max_length=100)

    gender = models.CharField(
        max_length=254,
        choices=GENDER_CHOICES,
        help_text='Genero'
    )

    relationship_hh = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=HOUSEHOLD_RELATIONSHIPS_CHOICES,
        help_text='Relacionamento com o agregado?'
    )

    occupation = models.IntegerField(null=True, blank=True)

    academic_level = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=ACADEMIC_LEVEL_CHOICES,
        help_text='Nivel de Academico'
    )

    marital_status = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=MARITAL_STATUS_CHOICES,
        help_text='Estado Civil?'
    )

    is_head_of_hh = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=YESNO_CHOICES,
        help_text='E responsavel do agregado?'
    )

    is_leaving_at_house = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=YESNODONTKNOW_CHOICES,
        help_text='Vive habitualmente na casa?'
    )

    is_sleeping_for_weeks = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=YESNODONTKNOW_CHOICES,
        help_text='Dormiu nas ultimas duas semanas?'
    )

    is_elegible_age = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        choices=YESNODONTKNOW_CHOICES,
        help_text='Tem mais de 15 anos?'
    )

    eligible_for_sputum = models.CharField(null=True, choices=YESNO_CHOICES, blank=True, max_length=2)
    case_control_score = models.IntegerField(null=True, blank=True)
    latest_stage = models.CharField(null=True, blank=True, max_length=20, choices=STAGES)
    creation_date = models.DateTimeField(null=True, blank=True)

    @property
    def review(self):
        return Medical_review.objects.filter(participant_id=self.pin).first()

    @property
    def central_cxr_reading(self):
        return CentralCXRReading.objects.filter(participant=self).first()

    @property
    def is_case_control(self):
        if not self.case_control_score:
            self.case_control_score = randint(0, 100)
            self.save()
        return self.case_control_score < 12

    def is_eligible_for_sputum(self):
        return self.eligible_for_sputum == YES

    def generate_next_pin(self):
        if Participant.objects.count() == 0:
            # return '%s%s001' % (self.census.cluster_code, self.census.household_number)
            next_pin_seq = 1
        else:

nsinya/templates/census/check_eligibility.html
{% extends "xf_viz_base.html" %}

{% block main %}
    <div class="col-md-12 col-sm-12 col-xs-12">
        {% for message in messages %}
            {% if forloop.first %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endif %}
        {% endfor %}
        <div class="x_panel">

            <div class="x_title">
                <h2>Eligibilidade para colheita de amostra</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <form class="form-horizontal form-label-left" method="post"
                      action="{% url 'nsinya:check-eligibility' %}">
                    {% csrf_token %}

                    <div class="form-group">
                        <label class="col-sm-2 control-label">PIN</label>
                        <div class="col-sm-4">
                            <div class="input-group">
                                <input type="text" class="form-control" name="pin" id="pin"
                                       required="required" autofocus="autofocus" onChange="this.form.submit();">
                                <span class="input-group-btn">
                                        <button type="submit" class="btn btn-primary">Verificar</button>
                                    </span>
                            </div>
                        </div>
                    </div>
                </form>
                {% if xray %}
                    <div class="row">
                        <label class="control-label col-md-2 col-sm-2  col-xs-12 col-md-offset-2" for="name">Xray status:</label>
                        <div class="control-value col-md-3 col-sm-3 col-xs-12">{{ xray.get_xray_status_display|default_if_none:'' }}</div>
                    </div>
                    <div class="row">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12 col-md-offset-2" for="name">Xray results:</label>
                        <div class="control-value col-md-3 col-sm-3 col-xs-12">{{ xray.get_xray_results_display|default_if_none:'' }}</div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

nsinya/templates/census/household_dashboard.html
{% extends "xf_viz_base.html" %}
{% load nsinya_filters %}
{% block main %}

    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">

            <div class="x_title">
                <h2>Household {{ household.household_number }}</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content" style="height: 140px; padding: 0em 1.5em; margin-bottom: 3em; overflow: auto">

                <div class="row">
                    <label class="control-label col-md-6 col-sm-6 col-xs-12">Household number:</label>
                    <div class="control-value col-md-6 col-sm-6 col-xs-12">{{ household.household_number }}</div>
                </div>
                <div class="row">
                    <label class="control-label col-md-6 col-sm-6 col-xs-12">Location:</label>
                    <div class="control-value col-md-6 col-sm-6 col-xs-12">{{ household.village }}, {{ household.locality }}, {{ household.administrative_post }}</div>
                </div>
                <div class="row">
                    <label class="control-label col-md-6 col-sm-6 col-xs-12">Visit Numer:</label>
                    <div class="control-value col-md-6 col-sm-6 col-xs-12">{{ household.visit_number }}</div>
                </div>
                <div class="row">
                    <label class="control-label col-md-6 col-sm-6 col-xs-12">Visit Date:</label>
                    <div class="control-value col-md-6 col-sm-6 col-xs-12">{{ household.visit_date }}</div>
                </div>
                <div class="row">
                    <label class="control-label col-md-6 col-sm-6 col-xs-12">Visit Result Start:</label>
                    <div class="control-value col-md-6 col-sm-6 col-xs-12">{{ household.get_visit_result_start_display }}</div>
                </div>
                <div class="row">
                    <label class="control-label col-md-6 col-sm-6 col-xs-12">Visit result end:</label>
                    <div class="control-value col-md-6 col-sm-6 col-xs-12">{{ household.get_visit_result_end_display }}</div>
                </div>
            </div>
            <div class="clearfix"></div>
            <h5>Members</h5>
            <div class="x_content">
                <table id="datatable-checkbox"
                       class="table table-striped table-bordered bulk_action">
                    <thead>
                    <tr>
                        <th>Pin</th>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Gender</th>
                        <th>Latest Stage</th>
                    </tr>
                    </thead>

                    <tbody>

                    {% for member in members %}

                        <tr>
                            <td>{{ member.pin }}</td>
                            <td>{{ member.name }} {{ member.surname }}</td>
                            <td>{{ member.age }}</td>
                            <td>{{ member.get_gender_display }}</td>
                            <td>{{ member.get_latest_stage_display}}</td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

nsinya/templates/census/household_listing.html
{% extends "xf_viz_base.html" %}

{% block main %}

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Households List</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>


                <div class="row">

                    <div class="x_content">
                        <table id="datatable-checkbox"
                               class="table table-striped table-bordered bulk_action">
                            <thead>
                            <tr>
                                <th>Household #</th>
                                <th>Location</th>
                                <th>Visit Number</th>
                                <th>Visit date</th>
                                <th>Visit Result Start</th>
                                <th>Visit Result End</th>
                                <th width="50"></th>
                            </tr>
                            </thead>

                            <tbody>

                            {% for household in households %}

                                <tr>
                                    <td>{{ household.household_number }}</td>
                                    <td>{{ household.village }}, {{ household.locality }}, {{ household.administrative_post }}</td>
                                    <td>{{ household.visit_number }}</td>
                                    <td>{{ household.visit_date }}</td>
                                    <td>{{ household.get_visit_result_start_display }}</td>
                                    <td>{{ household.get_visit_result_end_display }}</td>
                                    <td>
                                        <button class="btn btn-primary btn-sm" type="button"
                                                onclick="location.href='{% url 'nsinya:household-dashboard' household_id=household.id %}'"
                                                title="View"><i class="fa fa-eye"></i> View
                                        </button>
                                        <!--<a class="btn btn-default btn-sm"
                                           href="{% url 'admin:nsinya_census_change' household.id %}"
                                           title="Edit" target="_blank"><i class="fa fa-pencil"></i> Edit</a>-->
                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block starterjs %}
    $('#datatable-checkbox').DataTable();
{% endblock %}

nsinya/templates/census/participant_listing.html
{% extends "xf_viz_base.html" %}
{% load nsinya_filters %}

{% block main %}

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Participants List</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                    </ul>
                    <div class="clearfix"></div>
                </div>


                <div class="row">

                    <div class="x_content">
                        <table id="datatable-checkbox"
                               class="table table-striped table-bordered bulk_action">
                            <thead>
                            <tr>
                                <th>Pin</th>
                                {% if not hide_name %}<th>Name</th>{% endif %}
                                <th>Age</th>
                                <th>Gender</th>
                                <th>Latest Stage</th>
                                <th width="50"></th>
                            </tr>
                            </thead>

                            <tbody>

                            {% for participant in participants %}

                                <tr>
                                    <td>{{ participant.pin }}</td>
                                    {% if not hide_name %}<td>{{ participant.name }} {{ participant.surname }}</td>{% endif %}
                                    <td>{{ participant.age }}</td>
                                    <td>{{ participant.get_gender_display }}</td>
                                    <td>{{ participant.get_latest_stage_display }}</td>
                                    <td>
                                        <button class="btn btn-primary btn-sm" type="button"
                                                onclick="location.href='{% url 'nsinya:participant-dashboard' pin=participant.pin %}'"
                                                title="View"><i class="fa fa-eye"></i> View
                                        </button>
                                        <!--<a class="btn btn-default btn-sm"
                                           href="{% url 'admin:nsinya_participant_change' participant.id %}"
                                           title="Edit" target="_blank"><i class="fa fa-pencil"></i> Edit</a> -->
                                    </td>

                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

{% block starterjs %}
    $('#datatable-checkbox').DataTable();
{% endblock %}