nsinya/api/urls.py
from django.conf.urls import url
from .views import GxAlertCreateAPIView, WidgetAPIView, ServerStatusAPIView, GxConnectCreateAPIView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    url(r'^api-token-auth/', obtain_auth_token),
    url(r'^gx/v1/gxa/test$', GxAlertCreateAPIView.as_view(), name='api-gx-alert-test'),
    url(r'^gx/v2/connect/ping$', ServerStatusAPIView.as_view(), name='api-gx-server-status'),
    url(r'^gx/v2/connect/dailydetails$', ServerStatusAPIView.as_view(), name='api-gx-daily-details'),
    url(r'^gx/v2/connect/test$', GxConnectCreateAPIView.as_view(), name='api-gx-connect-test'),
    url(r'^widget/v1/$', WidgetAPIView.as_view(), name='api-widget'),
]

nsinya/urls.py
from django.conf.urls import include, url
from .views import *

app_name = 'nsinya'

urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api/', include('nsinya.api.urls')),
    url(r'^census/eligibility/$', CheckEligibilityView.as_view(), name="check-eligibility"),
    url(r'^census/eligibility/(?P<pin>[\w{}.-]+)/$', CheckEligibilityView.as_view(), name="check-eligibility"),
    url(r'^census/participants/$', ParticipantListingView.as_view(), name="participant-listing"),
    url(r'^census/participant/(?P<pin>[\w{}.-]+)/$', ParticipantDashboardView.as_view(), name="participant-dashboard"),
    url(r'^census/households/$', HouseholdListingView.as_view(), name="household-listing"),
    url(r'^census/household/(?P<household_id>[\w{}.-]+)/$', HouseholdDashboardView.as_view(), name="household-dashboard"),
    url(r'^diagnosis/sampletracking/$', SampleTrackingView.as_view(), name="sample-tracking"),
    url(r'^diagnosis/sample/(?P<sample_id>.+)/$', SampleDashboardView.as_view(), name="sample-tracking-dashboard"),
    url(r'^diagnosis/medical_review_panel/$', MedicalReviewPanelView.as_view(), name="medical-review_panel"),
    url(r'^diagnosis/review_participant/(?P<pin>[\w{}.-]+)/$', ReviewParticipantView.as_view(), name="review-participant"),
    url(r'^radiology/central_cxr_reading_list/$', CentralCXRReadingList.as_view(), name="central-cxr-reading-list"),
    url(r'^radiology/central_cxr_reading/(?P<pin>[\w{}.-]+)/$', CentralCXRReading.as_view(), name="read-participant-cxr"),
    url(r'^crl/reception/$', BatchReceptionView.as_view(), name="batch-reception"),
    url(r'^crl/receive/batch/(?P<batch_id>[0-9]+)/$', ReceiveBatchView.as_view(), name="receive-batch"),
    url(r'^crl/receive/sample/(?P<batch_id>[0-9]+)/$', ReceiveSampleView.as_view(), name="receive-sample"),
    url(r'^crl/receive/sample/(?P<batch_id>[0-9]+)/(?P<sample_id>\w+)/$', ReceiveSampleView.as_view(), name="receive-sample"),
    url(r'^crl/orphan_sample/$', ReceiveOrphanSampleView.as_view(), name="receive-orphan-sample"),
    url(r'^crl/orphan_sample/(?P<sample_id>\w+)/$', ReceiveOrphanSampleView.as_view(), name="receive-orphan-sample"),
    url(r'^crl/culture/$', CultureListingView.as_view(), name="culture-listing"),
    url(r'^crl/culture_reading/$', CultureReadingView.as_view(), name="culture-reading"),
    url(r'^crl/culture_reading/(?P<sample_id>\w+)/$', CultureReadingView.as_view(), name="culture-reading"),
    url(r'^crl/culture_edit/(?P<culture_id>\w+)/$', CultureEditView.as_view(), name="culture-edit"),
    url(r'^crl/culture_validation/$', CultureValidationView.as_view(), name="culture-validation"),
    url(r'^crl/culture_validation/(?P<sample_id>.+)/$', CultureValidationView.as_view(), name="culture-validation"),
    url(r'^crl/culture/validate/(?P<culture_id>.+)/$', ValidateCultureView.as_view(), name="validate-culture"),
    url(r'^crl/cultures/validate/$', ValidateCulturesView.as_view(), name="validate-cultures"),
    url(r'^crl/cultures/validate/(?P<sample_id>\w+)/$', ValidateCulturesView.as_view(), name="validate-cultures"),
    url(r'^crl/tsa/$', TSAListingView.as_view(), name="tsa-listing"),
    url(r'^crl/tsa/create/$', TSACreateView.as_view(), name="create-tsa"),
    url(r'^crl/tsa/create/(?P<sample_id>\w+)/$', TSACreateView.as_view(), name="create-tsa"),
    url(r'^crl/tsa_validation/$', TSAValidationView.as_view(), name="tsa-validation"),
    url(r'^crl/smear/$', SmearListingView.as_view(), name="smear-listing"),
    url(r'^crl/smear/(?P<sample_id>\w+)/$', SmearListingView.as_view(), name="smear-listing"),
    url(r'^crl/smear_validation/$', ValidateSmearView.as_view(), name="validate-smear"),
    url(r'^crl/smear_validation/(?P<sample_id>.+)/$', ValidateSmearView.as_view(), name="validate-smear"),
    url(r'^crl/worksheet/$', WorksheetView.as_view(), name="worksheet-creation"),
    url(r'^crl/worksheet/(?P<sample_id>\w+)/$', WorksheetView.as_view(), name="worksheet-creation"),
    url(r'^crl/worksheet/(?P<sample_id>\w+)/(?P<remove>\w+)$', WorksheetView.as_view(), name="worksheet-creation"),
    url(r'^crl/worksheet_select_type/(?P<sample_id>\w+)/(?P<type>\w+)$', WorksheetView.as_view(), name="worksheet-creation"),
    url(r'^crl/worksheet_select_type/(?P<type>\w+)/$', WorksheetView.as_view(), name="worksheet-creation"),
    url(r'^crl/worksheet_details/(?P<worksheet_code>[\w{}.-]+)/$', WorksheetDetailsView.as_view(), name="worksheet-details"),
    url(r'^crl/worksheetlist/$', WorksheetListView.as_view(), name="worksheet-list"),
    url(r'^crl/worksheetlist/(?P<worksheet_id>\w+)/$', WorksheetListView.as_view(), name="worksheet-list"),
    url(r'^crl/worksheetedit/(?P<worksheet_id>\w+)/$', WorksheetEditView.as_view(), name="worksheet-edit"),
    url(r'^crl/worksheetedit/(?P<sample_id>\w+)/(?P<worksheet_id>\w+)/(?P<remove>\w+)$', WorksheetEditView.as_view(), name="worksheet-edit-list"),
    url(r'^crl/inoculation/$', WorksheetInoculationView.as_view(), name="worksheet-inoculation"),
    url(r'^crl/inoculation/(?P<worksheet_id>\w+)/$', WorksheetInoculationView.as_view(), name="worksheet-inoculation"),
    url(r'^diagnosis/genexpert/$', GeneXpertListingView.as_view(), name="genexpert-listing"),
    url(r'^config/clusters/$', ClusterActivationView.as_view(), name="cluster-activation"),
    url(r'^census/cluster/(?P<cluster_id>[0-9]+)/$', ClusterBatchesView.as_view(), name="cluster-batches"),
    url(r'^census/cluster/(?P<cluster_code>[0-9]+)/status/(?P<status>[0-9]+)/$', ClusterStatusUpdateView.as_view(), name="cluster-status-update"),
    url(r'^crl/genotype_cm/$', Genotype_CMListingView.as_view(), name="genotype_cm-listing"),
    url(r'^crl/genotype_cm/(?P<sample_id>\w+)/$', Genotype_CMListingView.as_view(), name="genotype_cm-listing"),
    url(r'^crl/genotype_cm_validation/$', ValidateGenotypeCmView.as_view(), name="validate-genotype_cm"),
    url(r'^crl/genotype_cm_validation/(?P<sample_id>.+)/$', ValidateGenotypeCmView.as_view(), name="validate-genotype_cm"),
    url(r'^crl/genotype_mt/$', Genotype_MTListingView.as_view(), name="genotype_mt-listing"),
    url(r'^crl/genotype_mt/(?P<sample_id>\w+)/$', Genotype_MTListingView.as_view(), name="genotype_mt-listing"),
    url(r'^crl/genotype_mt_validation/$', ValidateGenotypeMtView.as_view(), name="validate-genotype_mt"),
    url(r'^crl/genotype_mt_validation/(?P<sample_id>.+)/$', ValidateGenotypeMtView.as_view(), name="validate-genotype_mt"),
    url(r'^crl/ziehl/$', ZiehlListingView.as_view(), name="ziehl-listing"),
    url(r'^crl/ziehl/(?P<sample_id>\w+)/$', ZiehlListingView.as_view(), name="ziehl-listing"),
    url(r'^crl/ziehl_validation/$', ValidateZiehlView.as_view(), name="validate-ziehl"),
    url(r'^crl/ziehl_validation/(?P<sample_id>.+)/$', ValidateZiehlView.as_view(), name="validate-ziehl"),
]

nsinya/forms.py
from bootstrap_datepicker.widgets import DatePicker
from django import forms
from .models import Batch_reception, Reception_CRL, Culture, TSA, Medical_review, CentralCXRReading
from django.forms import TextInput, NumberInput, Select, Textarea, RadioSelect
from .custom_widgets import *


class BatchReceptionForm(forms.ModelForm):
    class Meta:
        model = Batch_reception
        exclude = ['batch_id', 'received_by', 'reception_date', 'total_received_samples']

        widgets = {
            'temperature': NumberInput(attrs={'class': 'form-control input-sm', 'autofocus': 'autofocus', 'step': "0.01"}),
        }


class SampleReceptionForm(forms.ModelForm):
    class Meta:
        model = Reception_CRL
        exclude = ['sample_id', 'batch_id', 'received_by', 'reception_date']
        fields = ['acceptability', 'sample_aspect',  'quantity', 'rejection_reason', 'problematic_sample', 'comments']

        labels = {
            "quantity": "Volume(ml)",
        }

        widgets = {
            'quantity': NumberInput(attrs={'class': 'form-control input-sm', 'min': 0, 'max': '50', 'step': "0.01"}),
            'sample_aspect': Select(attrs={'class': 'form-control input-sm'}),
            'acceptability': Select(attrs={'class': 'form-control input-sm'}),
            'rejection_reason': Select(attrs={'class': 'form-control input-sm', 'disabled':'disabled'}),
            'problematic_sample': Select(attrs={'class': 'form-control input-sm', 'disabled':'disabled'}),
            'comments': Textarea(attrs={'class': 'form-control input-sm','rows':3}),
        }

    def __init__(self, *args, **kwargs):
        super(SampleReceptionForm, self).__init__(*args, **kwargs)
        self.fields['rejection_reason'].required = False
        self.fields['problematic_sample'].required = False


class CultureForm(forms.ModelForm):
    class Meta:
        model = Culture
        exclude = ['technician_name', 'result_date', 'update_date', 'validated_by_name', 'validated_by', 'validation_date']

        widgets = {
            'sample_id': TextInput(attrs={'class': 'form-control input-sm', 'readonly':'readonly'}),
            'culture_result': Select(attrs={'class': 'form-control input-sm'}),
            'positivity_week': Select(attrs={'class': 'form-control input-sm'}),
            'gradation': Select(attrs={'class': 'form-control input-sm', 'disabled':'disabled'}),
            'tube': Select(attrs={'class': 'form-control input-sm'}),
        }

    def __init__(self, *args, **kwargs):
        super(CultureForm, self).__init__(*args, **kwargs)
        #self.fields['positivity_week'].required = False
        self.fields['gradation'].required = False


class TSAForm(forms.ModelForm):
    class Meta:
        model = TSA
        exclude = ['sample_id', 'technician_code', 'result_date', 'validated_by', 'validation_date']

        labels = {
            "blood_result": "Blood Agar Plate",
            "TSA_1_H_result": "H",
            "TSA_1_R_result": "R",
            "TSA_1_Z_result": "Z",
            "TSA_1_E_result": "E",
            "TSA_1_S_result": "S",
            "TSA_2_Am_result": "AM",
            "TSA_2_Ka_result": "KA",
            "TSA_2_Cm_result": "CM",
            "TSA_2_Ofl_result": "OFL",
        }

        widgets = {
            'blood_result': Select(attrs={'class': 'form-control input-sm'}),
            'TSA_1_H_result': Select(attrs={'class': 'form-control input-sm'}),
            'TSA_1_R_result': Select(attrs={'class': 'form-control input-sm'}),
            'TSA_1_Z_result': Select(attrs={'class': 'form-control input-sm'}),
            'TSA_1_E_result': Select(attrs={'class': 'form-control input-sm'}),
            'TSA_1_S_result': Select(attrs={'class': 'form-control input-sm'}),
            'TSA_2_Am_result': Select(attrs={'class': 'form-control input-sm'}),
            'TSA_2_Ka_result': Select(attrs={'class': 'form-control input-sm'}),
            'TSA_2_Cm_result': Select(attrs={'class': 'form-control input-sm'}),
            'TSA_2_Ofl_result': Select(attrs={'class': 'form-control input-sm'}),
            'acceptability': Select(attrs={'class': 'form-control input-sm'}),
        }

    def __init__(self, *args, **kwargs):
        super(TSAForm, self).__init__(*args, **kwargs)


class MedicalReviewForm(forms.ModelForm):
    class Meta:
        model = Medical_review
        exclude = ['participant_id', 'review_date', 'panel_representative']

        widgets = {
            'tb_case': Select(attrs={'class': 'form-control input-sm'}),
            'remarks': Textarea(attrs={'class': 'form-control input-sm'}),
        }

    def __init__(self, *args, **kwargs):
        super(MedicalReviewForm, self).__init__(*args, **kwargs)
        self.fields['remarks'].required = False


class CentralCXRReadingForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CentralCXRReadingForm, self).__init__(*args, **kwargs)

    class Meta:
        model = CentralCXRReading
        exclude = ['participant', 'creation_date', 'update_date']

        widgets = {
            'cxr_reading_result': Select(attrs={'class': 'form-control input-sm','required':True}),
            'cavity': HorizontalRadioSelect(attrs={'disabled': 'disabled'}),
            'infiltrate': HorizontalRadioSelect(attrs={'disabled': 'disabled'}),
            'lung_nodules': HorizontalRadioSelect(attrs={'disabled': 'disabled'}),
            'pleural_effusion': HorizontalRadioSelect(attrs={'disabled': 'disabled'}),
            'mediastinal_lymphadenopathy': HorizontalRadioSelect(attrs={'disabled': 'disabled'}),
            'hilar_lymphadenopathy': HorizontalRadioSelect(attrs={'disabled': 'disabled'}),
            'discipleship': HorizontalRadioSelect(attrs={'disabled': 'disabled'}),
            'cxr_final_reading_result': Select(attrs={'class': 'form-control input-sm', 'disabled': 'disabled'}),
            'reading_status': Select(attrs={'class': 'form-control input-sm'}),
        }

nsinya/api/views.py
from rest_framework.generics import CreateAPIView
from rest_framework.views import APIView
from nsinya.serializers import GeneXpertSerializer
from rest_framework import status
from rest_framework.response import Response
from . import gx_utils, widget_utils


class GxAlertCreateAPIView(CreateAPIView):
    serializer_class = GeneXpertSerializer

    def perform_create(self, serializer):
        gx_utils.create_gx(serializer=serializer)


class GxConnectCreateAPIView(CreateAPIView):
    authentication_classes = ()
    permission_classes = ()
    serializer_class = GeneXpertSerializer

    def perform_create(self, serializer):
        gx_utils.create_gx(serializer=serializer)


class WidgetAPIView(APIView):
    request = None
    pin = None

    def get(self, request):
        request_type_mapping = {"stagestatus": self.check_stage_status,
                                "sampleid": self.validate_sample_id,
                                "batchid": widget_utils.get_next_batch_id,
                                "case_control_evaluator": self.evaluate_case_control_eligibility
                                }

        request_types = ("stagestatus", "sampleid", "batchid", "case_control_evaluator")
        request_type = request.query_params.get('requesttype', None)

        self.request = request

        if request_type not in request_types:
            return Response(data='Unknown request type', status=status.HTTP_400_BAD_REQUEST)

        self.pin = request.query_params.get('pin', None)

        return request_type_mapping[request_type]()

    def validate_sample_id(self):
        suffix = self.request.query_params.get('suffix', None)
        return widget_utils.validate_sample_id(pin=self.pin, suffix=suffix)

    def check_stage_status(self):
        form_id = self.request.query_params.get('formid', None)
        stage_status_validation = widget_utils.StageStatusValidation()

        return widget_utils.StageStatusValidation.validate_stage(self=stage_status_validation, form_id=form_id, pin=self.pin)

    def evaluate_case_control_eligibility(self):
        return widget_utils.evaluate_case_control_eligibility(pin=self.pin)


class ServerStatusAPIView(APIView):
    authentication_classes = ()
    permission_classes = ()

    def post(self, request, format=None):
        return Response(data="200", status=status.HTTP_200_OK)

nsinya/templates/crl/culture_reading.html
{% extends "xf_viz_base.html" %}

{% block main %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('[name="culture_result"]').change(function () {
                var result = this.value;

                if (result == '1') {
                    $('[name="gradation"]').prop('disabled', false);
                    $('[name="gradation"]').prop('required', true);
                }
                else {
                    $('[name="gradation"]').prop('value', '');
                    $('[name="gradation"]').prop('disabled', true);
                    $('[name="gradation"]').prop('required', false);
                }
            })
        });
    </script>
    <div class="col-md-12 col-sm-12 col-xs-12">
        {% for message in messages %}
            {% if forloop.first %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endif %}
        {% endfor %}

        <div class="x_panel">
            <div class="x_title">
                <h2>Culture Reading</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                {% if not sample_id %}
                    <form class="form-horizontal form-label-left" method="post"
                          action="{% url 'nsinya:culture-reading' %}">
                        {% csrf_token %}

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Sample ID</label>
                            <div class="col-sm-4">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="sampleid" id="sampleid"
                                           required="required" autofocus="autofocus" onChange="this.form.submit();">
                                    <span class="input-group-btn">
                                        <button type="submit" class="btn btn-primary">Find Sample</button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </form>
                {% else %}
                    <form class="form-horizontal form-label-left"
                          action="{% url 'nsinya:culture-reading' sample_id=sample_id %}"
                          method="post">
                        {% csrf_token %}
                        {% for field in form %}

                            <div class="form-group has-feedback">
                                <label class="control-label col-sm-2"
                                       for="id_{{ field.name }}">{{ field.label }}</label>
                                <div class="col-sm-3">
                                    {{ field }}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="clearfix"></div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-2">
                                <button type="submit" class="btn btn-primary ">Save</button>
                                <button class="btn btn-primary " type="button" title="Find Sample"
                                        onclick="location.href='{% url 'nsinya:culture-reading' %}'">Next Sample
                                </button>
                            </div>
                        </div>
                    </form>

                    <div class="clearfix"></div>
                    <h2>Previous readings</h2>
                    <table id="datatable-checkbox"
                           class="table table-striped table-bordered bulk_action">
                        <thead>
                        <tr>
                            <th>Positivity week</th>
                            <th>Culture result</th>
                            <th>Gradation</th>
                            <th>Tube</th>
                            <th>Technician name</th>
                            <th>Result Date</th>
                            <th>Validated by</th>
                            <th>Validation Date</th>
                            <th></th>
                        </tr>
                        </thead>

                        <tbody>

                        {% for culture in cultures %}

                            <tr>
                                <td>{{ culture.get_positivity_week_display }}</td>
                                <td>{{ culture.get_culture_result_display }}</td>
                                <td>{{ culture.get_gradation_display|default_if_none:'' }}</td>
                                <td>{{ culture.get_tube_display|default_if_none:'' }}</td>
                                <td>{{ culture.technician_name }}</td>
                                <td>{{ culture.result_date }}</td>
                                <td>{{ culture.validated_by.get_full_name|default_if_none:'' }}</td>
                                <td>{{ culture.validation_date|default_if_none:'' }}</td>
                                <td>
                                    {% if show_edit_button and culture.validated_by is None %}
                                        <button class="btn btn-primary btn-sm" type="button" title="Edit"
                                                onclick="location.href='{% url 'nsinya:culture-edit' culture_id=culture.id %}'">
                                            <i class="fa fa-edit"></i> Edit
                                        </button>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

nsinya/templates/crl/culture_validation.html
{% extends "xf_viz_base.html" %}

{% block main %}

    <div class="col-md-12 col-sm-12 col-xs-12">
        {% for message in messages %}
            {% if forloop.first %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endif %}
        {% endfor %}

        <div class="x_panel">
            <div class="x_title">
                <h2>Culture Reading Validation</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                {% if not sample_id %}
                    <form class="form-horizontal form-label-left" method="post"
                          action="{% url 'nsinya:culture-validation' %}">
                        {% csrf_token %}

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Sample ID</label>
                            <div class="col-sm-4">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="sampleid" id="sampleid"
                                           required="required" autofocus="autofocus" onChange="this.form.submit();">
                                    <span class="input-group-btn">
                                        <button type="submit" class="btn btn-primary">Find Sample</button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </form>

                     <div class="clearfix"></div>
                    <form class="form-horizontal form-label-left"
                          action="{% url 'nsinya:validate-cultures' %}"
                          method="post">
                        {% csrf_token %}
                    <table id="datatable-checkbox"
                           class="table table-striped table-bordered bulk_action">
                        <thead>
                        <tr>
                            <th></th>
                            <th>Sample Id</th>
                            <th>Tube</th>
                            <th>Positivity week</th>
                            <th>Culture result</th>
                            <th>Gradation</th>
                            <th>Technician name</th>
                            <th>Result Date</th>
                        </tr>
                        </thead>

                        <tbody>

                        {% for culture in cultures %}

                            <tr>
                                <td>
                                    {% if not culture.validated_by %}
                                        <input type="checkbox"  name="selected_culture_id" value="{{ culture.id}}" class="flat">
                                    {% endif %}
                                </td>
                                <td>{{ culture.sample_id }}</td>
                                <td>{{ culture.tube }}</td>
                                <td>{{ culture.get_positivity_week_display }}</td>
                                <td>{{ culture.get_culture_result_display }}</td>
                                <td>{{ culture.get_gradation_display|default_if_none:'' }}</td>
                                <td>{{ culture.technician_name }}</td>
                                <td>{{ culture.result_date }}</td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                     {% if show_validate_button %}<button type="submit" class="btn btn-success"><i class="fa fa-check-square-o"></i> Validate</button>{% endif %}
                    </form>
                {% else %}
                    <form class="form-horizontal form-label-left"
                          action="{% url 'nsinya:validate-cultures' sample_id=sample_id %}"
                          method="post">
                        {% csrf_token %}
                    <h4>Sample: {{ sample_id }}</h4>
                    <table id="datatable-checkbox"
                           class="table table-striped table-bordered bulk_action">
                        <thead>
                        <tr>
                            <th></th>
                            <th>Tube</th>
                            <th>Positivity week</th>
                            <th>Culture result</th>
                            <th>Gradation</th>
                            <th>Technician name</th>
                            <th>Result Date</th>
                            <th>Validated by</th>
                            <th>Validation Date</th>
                        </tr>
                        </thead>

                        <tbody>

                        {% for culture in cultures %}

                            <tr>
                                <td>
                                    {% if not culture.validated_by %}
                                        <input type="checkbox"  name="selected_culture_id" value="{{ culture.id}}" class="flat">
                                    {% endif %}
                                </td>
                                <td>{{ culture.tube }}</td>
                                <td>{{ culture.get_positivity_week_display }}</td>
                                <td>{{ culture.get_culture_result_display }}</td>
                                <td>{{ culture.get_gradation_display|default_if_none:'' }}</td>
                                <td>{{ culture.technician_name }}</td>
                                <td>{{ culture.result_date }}</td>
                                <td>{{ culture.validated_by.get_full_name|default_if_none:'' }}</td>
                                <td>{{ culture.validation_date|default_if_none:'' }}</td>

                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                     {% if show_validate_button %}<button type="submit" class="btn btn-success"><i class="fa fa-check-square-o"></i> Validate</button>{% endif %}
                    </form>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

{% block starterjs %}
    $('#datatable-checkbox').DataTable();
{% endblock %}

nsinya/templates/crl/validate_culture.html
{% extends "xf_viz_base.html" %}

{% block main %}

    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">

            <div class="x_title">
                <h2>Validate Culture Reading</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <form class="" action="{% url 'nsinya:validate-culture' culture_id=culture.id%}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Sample id:</label>
                        <div class="control-value col-md-6 col-sm-6 col-xs-12">{{ culture.sample_id }}</div>
                    </div>
                    <div class="row">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Culture Result:</label>
                        <div class="control-value col-md-6 col-sm-6 col-xs-12">{{ culture.get_culture_result_display }}</div>
                    </div>
                    <div class="row">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Positivity Week:</label>
                        <div class="control-value col-md-6 col-sm-6 col-xs-12">{{ culture.get_positivity_week_display }}</div>
                    </div>
                    <div class="row">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Gradation:</label>
                        <div class="control-value col-md-6 col-sm-6 col-xs-12">{{ culture.get_gradation_display }}</div>
                    </div>
                    <div class="row">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Techinician code:</label>
                        <div class="control-value col-md-6 col-sm-6 col-xs-12">{{ culture.technician_name }}</div>
                    </div>
                    <div class="row">
                        <label class="control-label col-md-2 col-sm-2 col-xs-12">Result Date:</label>
                        <div class="control-value col-md-6 col-sm-6 col-xs-12">{{ culture.result_date }}</div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-primary">Validate</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}